[package]
name = "vscli"
version = "0.1.3"
edition = "2021"
authors = ["Michael Lohr <michael@lohr.dev>"]
description = "A CLI tool to launch vscode projects, which supports devcontainers."
readme = "README.md"
repository = "https://github.com/michidk/vscli"
documentation = "https://github.com/michidk/vscli"
homepage = "https://github.com/michidk/vscli"
license = "MIT"
keywords = ["development", "settings", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.3.4", features = ["derive", "color", "help", "usage", "suggestions"] }
color-eyre = "0.6.2"
env_logger = "0.10.0"
hex = "0.4.3"
log = "0.4.17"
serde_json = "1.0.93"
wslpath2 = "0.1.0"
