name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to (e.g. 0.1.0)'
        type: 'string'
        required: true

permissions:
  contents: write

jobs:
  bump_version:
    uses: stellar/actions/.github/workflows/rust-bump-version.yml@main
    with:
      version: ${{ github.event.inputs.version }}
